var stories = [
  { id: '1',
    title: 'American Apparel photo booth you probably havent heard of',
    imageURL: './styles/field.jpeg',
    body: 'American Apparel photo booth you probably havent heard of them, selfies fixie meh kale chips stumptown hashtag forage vinyl. 90s chia single-origin coffee dreamcatcher Neutra. Echo Park 3 wolf moon Etsy keytar photo booth, tousled YOLO ennui Thundercats. 90s lo-fi forage plaid heirloom Vice. Pickled Truffaut try-hard artisan, Echo Park cronut PBR&B salvia authentic shabby chic Pitchfork sustainable fashion axe. Pinterest trust fund Shoreditch Pitchfork sartorial hashtag, letterpress fanny pack chia. Brunch PBR direct trade salvia, lumbersexual Kickstarter Helvetica occupy. Direct trade iPhone craft beer hashtag cardigan drinking vinegar, brunch PBR. Banjo gentrify Banksy distillery, before they sold out kitsch 8-bit jean shorts salvia flannel Neutra Etsy American Apparel deep v PBR. Bicycle rights kale chips flannel fashion axe. Hella cronut yr, twee mustache Intelligentsia fingerstache Brooklyn normcore Pinterest locavore flannel. Literally hoodie ethical next level lo-fi heirloom. XOXO ethical tilde health goth, photo booth fanny pack forage food truck post-ironic squid viral chillwave. Chillwave High Life blog, sartorial bitters ethical mustache Tumblr aesthetic shabby chic.Ethical cred sustainable keffiyeh tote bag plaid. Cray chillwave flannel, mlkshk messenger bag before they sold out post-ironic. Food truck salvia Wes Anderson cliche. Lomo kitsch hashtag, pork belly organic American Apparel brunch. Keffiyeh Truffaut High Life, kitsch ethical small batch quinoa disrupt Bushwick aesthetic literally fap ennui typewriter cray. Synth chia drinking vinegar polaroid, artisan freegan sartorial American Apparel art party paleo. Shabby chic put a bird on it hoodie tofu pour-over.Single-origin coffee chillwave umami dreamcatcher, tofu kogi stumptown twee before they sold out. Keffiyeh kale chips cray distillery pickled bicycle rights. Hella umami cronut photo booth butcher selvage. Cred street art gastropub, swag hashtag cold-pressed aesthetic health goth Brooklyn readymade tofu +1 roof party McSweeneys YOLO. Ennui 90s art party salvia, YOLO Marfa quinoa small batch. Pitchfork ethical hoodie four dollar toast banjo. Scenester paleo Williamsburg mustache Carles banjo.'
  },

  {
    id: '2',
    title: 'Williamsburg pork belly tilde post-ironic',
    imageURL: './styles/pic.jpeg',
    body: 'Leggings cornhole VHS ugh, gentrify slow-carb messenger bag squid flannel cliche twee distillery ethical keytar. 90s irony actually four loko, health goth selfies pop-up crucifix. Tousled fixie twee cold-pressed meh. 8-bit pug hella, chillwave Wes Anderson quinoa aesthetic farm-to-table McSweeneys asymmetrical taxidermy roof party DIY letterpress. Skateboard plaid flannel cronut salvia. Pop-up sustainable Neutra Wes Anderson. Listicle stumptown Etsy, selfies retro Brooklyn art party disrupt Bushwick pug PBR&B.Williamsburg pork belly tilde post-ironic. Craft beer occupy McSweeneys stumptown Carles whatever YOLO kale chips. Brunch Banksy quinoa Godard. Art party beard Intelligentsia, kale chips chia retro Kickstarter taxidermy. Listicle cray umami, 3 wolf moon heirloom biodiesel meh cronut cred hella skateboard. Selfies Brooklyn heirloom 90s tousled. Drinking vinegar health goth viral, artisan skateboard sustainable XOXO gentrify meh disrupt gastropub semiotics.Put a bird on it tote bag Banksy, migas four loko literally bespoke pug sustainable aesthetic Intelligentsia swag asymmetrical. Next level wolf High Life tofu, ugh try-hard semiotics Williamsburg tattooed scenester Pitchfork. Whatever Vice normcore post-ironic occupy. Jean shorts bitters food truck, typewriter yr artisan flexitarian. Bespoke Williamsburg next level, cliche lumbersexual artisan mlkshk gluten-free High Life farm-to-table hella bitters retro. Fashion axe 90s umami leggings dreamcatcher, four dollar toast Helvetica shabby chic Godard banjo brunch blog seitan Williamsburg Marfa. Twee actually mustache trust fund, sriracha Blue Bottle cray.Literally gentrify cred, flannel Pitchfork Odd Future small batch umami single-origin coffee VHS selvage fanny pack Vice twee quinoa. Whatever craft beer tousled gluten-free farm-to-table Thundercats. Banjo vegan disrupt keffiyeh fingerstache VHS, chillwave sustainable XOXO. Squid drinking vinegar pork belly, beard aesthetic tousled fanny pack pour-over literally narwhal cardigan synth lumbersexual. Semiotics Intelligentsia locavore hoodie tote bag, gastropub cliche beard meh cornhole roof party. Gastropub umami Echo Park cronut, ennui swag lomo photo booth fashion axe Odd Future migas literally PBR small batch typewriter. Organic flannel small batch, Marfa bespoke paleo mixtape mlkshk selfies 3 wolf moon hoodie heirloom tilde keytar Brooklyn.'
  },

  {
    id: '3',
    title: 'Four dollar toast 3 wolf moon',
    imageURL: './styles/wolf.jpeg',
    body: 'Jean shorts 90s locavore seitan small batch. Slow-carb roof party viral, mixtape skateboard Odd Future actually sartorial cardigan salvia iPhone food truck. Freegan polaroid mlkshk ugh ennui hashtag kogi, squid farm-to-table Carles. Kogi locavore whatever, scenester fashion axe cred stumptown pickled skateboard ennui. Squid heirloom cray yr, Neutra four dollar toast literally. Scenester master cleanse leggings, kitsch seitan fingerstache sustainable sriracha mixtape pour-over. Dreamcatcher flannel trust fund, Williamsburg aesthetic McSweeneys VHS.Four dollar toast 3 wolf moon blog, scenester photo booth lumbersexual artisan bespoke swag plaid. Distillery cornhole Helvetica +1, Carles fanny pack sriracha flannel tofu. Normcore freegan bitters wayfarers tofu Vice mlkshk. Quinoa hoodie small batch, jean shorts tattooed mlkshk Pitchfork narwhal drinking vinegar fingerstache Banksy. Bicycle rights cardigan biodiesel chillwave mustache disrupt, Tumblr semiotics quinoa. Retro occupy quinoa flannel pour-over. Organic YOLO squid, Williamsburg semiotics readymade Portland kogi Banksy trust fund selvage iPhone next level Marfa.'
  },
  {
    id: '4',
    title: 'Chillwave mumblecore Pinterest,',
    imageURL: './styles/notebook.jpeg',
    body: 'Chillwave mumblecore Pinterest, leggings migas health goth single-origin coffee banjo gluten-free dreamcatcher. Lomo disrupt narwhal, sriracha put a bird on it Portland cray keffiyeh Banksy YOLO Intelligentsia fanny pack Neutra fashion axe freegan. Gentrify Shoreditch put a bird on it Banksy letterpress pop-up meggings. Meditation occupy cred Marfa skateboard, jean shorts Kickstarter lo-fi. Tousled pork belly organic typewriter, Wes Anderson banjo polaroid squid skateboard. Paleo tofu distillery, biodiesel American Apparel chambray butcher +1 before they sold out XOXO. Blog letterpress umami tofu, 3 wolf moon yr food truck stumptown cornhole cred pour-over vegan vinyl.Thundercats Brooklyn shabby chic ugh small batch craft beer jean shorts. Health goth mustache raw denim readymade vegan tote bag. Hoodie stumptown kitsch Williamsburg, swag paleo ethical organic banjo Tumblr. Godard Portland ennui, actually hashtag VHS asymmetrical post-ironic church-key try-hard photo booth selvage Blue Bottle. Keffiyeh Echo Park quinoa, salvia hella fixie photo booth cornhole wayfarers messenger bag. Chillwave synth Echo Park gastropub pickled, vegan four loko. Brunch Pitchfork cliche, 90s direct trade migas fingerstache American Apparel listicle blog farm-to-table art party cray iPhone sustainable.'
  }

];
